version: '3.8'

services:
  frontend:
    build: .
    image: youttala_backend:latest
    container_name: youttala_backend
    ports:
      - "3002:3002"
    networks:
        websites:
          ipv4_address: 172.20.0.11
    environment:
      - "REACT_APP_BACKEND_URL=http://localhost:3002"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

# https://devopswithdocker.com/part2/ Containers in development
volumes:
  node_modules:

networks:
   websites:
    name: websites
    external: true